MODEL:
  NUM_CLASSES: 11
  BACKBONE:
    NAME: 'mobilenet_v2'
    OUT_CHANNELS: (96, 1280, 512, 256, 256, 64)
  PRIORS:
    FEATURE_MAPS: [32, 16, 8, 4, 2, 1]
    STRIDES: [16, 32, 64, 128, 256, 512]
    MIN_SIZES: [20.48, 51.2, 133.12, 215.04, 296.96, 378.88]
    MAX_SIZES: [51.2, 133.12, 215.04, 296.96, 378.88, 460.8]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ("bdd_2020_train",)
  TEST: ("bdd_2020_val", )
SOLVER:
  MAX_ITER: 400000
  LR_STEPS: [280000, 360000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: '/media/ratnajit/scratch1/GODtraining/mobilenetv2_ssd512_bdd2020'